# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import table.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('fecha_emision', models.DateField(default=table.models.rand_date)),
                ('fecha_vencimiento', models.DateField(default=table.models.rand_date)),
                ('fecha_pago', models.DateTimeField(default=table.models.rand_date)),
                ('total', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('total2', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('total3', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=table.models.total_rand, max_digits=15)),
                ('referencia', models.UUIDField(default=uuid.uuid4, verbose_name='Referencia')),
                ('referencia2', models.UUIDField(default=uuid.uuid4, verbose_name='Referencia')),
                ('referencia3', models.UUIDField(default=uuid.uuid4, verbose_name='Referencia')),
                ('url', models.CharField(max_length=250)),
                ('url2', models.CharField(max_length=250)),
                ('url3', models.CharField(max_length=250)),
                ('factura_generica', models.BooleanField(default=table.models.rand_bool)),
                ('reconexion_aplicada', models.BooleanField(default=table.models.rand_bool, verbose_name='\xbfYa se aplico reconexi\xf3n?')),
                ('mora_aplicada', models.BooleanField(default=table.models.rand_bool, verbose_name='\xbfYa se aplico mora?')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente de pago'), (1, 'Pagada'), (2, 'Cancelada'), (3, 'En Revision'), (4, 'Se Transfirio')], default=table.models.rand_state)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('personas', models.UUIDField(default=uuid.uuid4)),
                ('personas2', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('eslogan', models.CharField(max_length=250)),
                ('rfc', models.CharField(default=uuid.uuid4, max_length=100)),
                ('rfc2', models.CharField(default=uuid.uuid4, max_length=100)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Editoriales', to='table.Distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.ImageField(upload_to='portadas')),
                ('autor', models.ManyToManyField(to='table.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('informacion', models.TextField(blank=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='table.Editorial')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.Perfil', verbose_name='Autores'),
        ),
    ]
