# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='editor',
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=40, verbose_name='Apellidos '),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre '),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
