# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.Ciudad', verbose_name='Ciudad'),
        ),
    ]
